type: object
description: Information about an NLP service
properties:
  name:
    description: The service name
    type: string
    minLength: 3
    maxLength: 60
    pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    example: awesome-date-annotator
  version:
    description: The version of the service (SemVer string)
    type: string
    minLength: 1
    pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
    example: 1.0.0
  license:
    # License keyword from GitHub:
    # https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository
    description: The license of this service (spdx.org/licenses Identifier)
    type: string
    enum:
      - afl-3.0
      - apache-2.0
      - artistic-2.0
      - bsl-1.0
      - bsd-2-clause
      - bsd-3-clause
      - bsd-3-clause-clear
      - cc
      - cc0-1.0
      - cc-by-4.0
      - cc-by-sa-4.0
      - wtfpl
      - ecl-2.0
      - epl-1.0
      - epl-2.0
      - eupl-1.1
      - agpl-3.0
      - gpl
      - gpl-2.0
      - gpl-3.0
      - lgpl
      - lgpl-2.1
      - lgpl-3.0
      - isc
      - lppl-1.3c
      - ms-pl
      - mit
      - mpl-2.0
      - osl-3.0
      - postgresql
      - ofl-1.1
      - ncsa
      - unlicense
      - zlib
    example: "apache-2.0"
  repository:
    description: The place where the code lives
    type: string
    example: "github:awesome-org/awesome-date-annotator"
  description:
    description: A short, one-sentence summary of the service
    type: string
    maxLength: 100
    example: "An awesome Date Annotator based on regex patterns"
  author:
    description: The author of the service
    type: string
    example: "Example Author"
  authorEmail:
    description: The email address of the author
    type: string
    format: email
    example: "author@example.com"
  url:
    description: The URL to the homepage of the service
    type: string
    format: uri