openapi: 3.0.2
info:
  version: 1.0.0
  title: NLP Sandbox Date Annotator API
  # termsOfService: 'https://data2health.github.io/nlp-sandbox-data-node-schemas/terms/'
  contact:
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://data2health.github.io/nlp-sandbox-schemas'
  license:
    name: Apache 2.0
    url: 'https://github.com/data2health/nlp-sandbox/blob/master/LICENSE'
  x-logo:
    url: 'https://data2health.github.io/nlp-sandbox-data-node-schemas/docs/logo.png'
  description: >
    The OpenAPI specification implemented by NLP Sandbox Date Annotators.

    # Overview

    This NLP tool detects date references in the clinical note specified and
    returns a list of date annotations.
tags:
  - name: Date
    description: Operations about dates
  - name: Health
    description: Operations about API health
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /dates:
    $ref: 'paths/dates.yaml'
  /health:
    $ref: '../commons/paths/health.yaml'