openapi: 3.0.2
info:
  version: 0.1.1
  title: NLP Sandbox Person Name Annotator API
  contact:
    name: The NLP Sandbox Team
    email: thomas.schaffter@sagebionetworks.org
    url: 'https://Sage-Bionetworks.github.io/nlp-sandbox-schemas'
  license:
    name: Apache 2.0
    url: 'https://github.com/Sage-Bionetworks/nlp-sandbox/blob/main/LICENSE'
  x-logo:
    url: 'https://Sage-Bionetworks.github.io/nlp-sandbox-schemas/logo.png'
  description: >
    The OpenAPI specification implemented by NLP Sandbox Person Name Annotators.

    # Overview

    This NLP tool detects references of person names in the clinical notes given
    as input and returns a list of person name annotations.
tags:
  - name: Person Name
    description: Operations about person names
  - name: Health
    description: Operations about API health
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /person-names:
    $ref: 'paths/person-names.yaml'
  /health:
    $ref: '../commons/paths/health.yaml'